### ISSUE TITLE
순서 변경

### ISSUE THREAD

**Issue by wpdbs1229** [OneK-2/OneK-2#1]
[![Onek-2's GitHub Stats](https://github-readme-stats.vercel.app/api?username=Onek-2&include_all_commits=true&show_icons=true&icon_color=424242)](https://github.com/anuraghazra/github-readme-stats)

[![OneK-2's solved.ac stats](https://github-readme-solvedac.hyp3rflow.vercel.app/api/?handle=wonk98)](https://solved.ac/profile/wonk98)

요거 2개를 나란히 오게해주시면 어떨까요..?

**Comment by OneK-2** [comment]
너무 길어요...
